build:
  version: "3.0"

accounts:
  message: "Welcome to Bank accounts related local APIs"
  contactDetails:
    name: "Ritik Ranjan"
    email: "ritikranjan999@gmail.com"
  onCallSupport:
    - +919876543210
    - +919087654321