server:
  port: 8071

spring:
  application:
    name: "configserver"

  profiles:
    active: git
  # active: native

  git:


  cloud:
    config:
      server:
        git:
          uri: https://github.com/MeRitik/bank-config.git
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
#        native:
#          search-locations: "file:///C:/config"
#          search-locations: "classpath:/config"
